#include<iostream>
#include<conio.h>
#include<time.h>
#include<windows.h>

using namespace std;

int life = 0;
int amount = 0;
int range_ref;
int range;

void load(int k) {
	char x = 219;
	cout << "//// CASINO ////" << endl;
	for (int i = 0; i <= 16 ; i++)
	{
        cout << x;
		Sleep(k);
	}
	cout << endl;
	system("cls");
}
int menu() {
	cout << "-------- WELCOME TO CASINO ----------" << endl;
	cout << "        1. Play " << endl;
	cout << "        2. About" << endl;
	cout << "        3. Exit" << endl;
	cout << "-------------------------------------" << endl;;
	int x;
	cout << "ENTER YOUR CHOICE : ";
	cin >> x;
	return x;
}
void get_data() {
	system("cls");
	cout << " ENTER TOTAL AMOUNT : "; cin >> amount;
	cout << " ENTER MAXIMUM LIFES : "; cin >> life;
	back:cout << " ENTER THE RANGE : "; cin >> range_ref;
	if (range_ref > 0) {
		range = range_ref;
	}
	else {
		cout << "RANGE CANNOT BE NEGATIVE !! " << endl;
		goto back;
	}
}
void try_ag() {
	system("cls");
	cout << "YOU LOST A LIFE ! TRY AGAIN " << endl;
	cout << "----------------------------";
	life--;
}
int random() {
	srand(time(0));
	int ref_rand = rand() % range;
	ref_rand = 3;
	return ref_rand;
}
void lose() {
	cout << "YOU LOSE ! ";
}
void win() {
	system("cls");
	cout << "CONGRATULATIONS !! " << endl;
	cout << "YOU WON !! " << endl;
	system("pause>0");
	cout << "PRESS ANY KEY TO CONTINUE !!" << endl;

}
void casino() {
	int guess;
    int bet_amt;
	int RANDOM = random();
	while ((amount != 0)) {
		come:system("cls");
		if (life == 0 || amount == 0) {
			lose();
			break;
		} else {
			cout << "LIFE : " << life << endl;
			cout << "RANGE : " << range << endl;
			cout << "BALANCE : " << amount << endl;
			loop1:cout << "ENTER BET AMOUNT : "; cin >> bet_amt;
			cout << "---- ----- -------- ----- ---------- ---- " << endl;
			if (bet_amt > amount) {
				cout << "Try Again !! " << endl << endl;
				goto loop1;
			}
			else {
				cout << "ENTER YOUR GUESS !! : "; cin >> guess;
				if (guess == RANDOM) {
					amount = amount + bet_amt;
					win();
				}
				else {
					if (amount == 0) {
						goto come;
					}
					else {
						amount = amount - bet_amt;
						cout << "LOST LIFE ! " << endl;
					}
					try_ag();
			}
			cout << "BET IS INVALID !! " << endl;
			cout << "|||  TRY AGAIN !! |||" << endl << endl;
			}
		}
	}
}
void about() {
	system("cls");
	cout << "-> This is a simple gambling game which is currently under development\nThis game is currently available for single players  " << endl;
	cout << " **** HOW TO PLAY ****" << endl;
	cout << "1. Player needs to enter total amount, range for guess and life parameters." << endl;
	cout << "2. And player starts the game by betting amount " << endl;
	cout << "3. The player should guess the number that is randomly generated by the COMPUTER " << endl;
	cout << "4. If the player will guess the number, then the betted amount is added to the amount or else it is deducted " << endl;
	cout << "4. If player looses all the lifes then he is eleminated from the game " << endl;
	cout << " ---- CLICK E TO GO BACK TO MENU ----" << endl;
	cout << "---- DEVELOPED OFFICIALLY BY NARASIMHA MURTHY ----" << endl;
	char a;
here:a = _getch();
	if ((a == 'E') || (a == 'e')) {
		system("cls");
	}
	else {
		cout << endl << "TRY AGAIN !! " << endl;
		goto here;
	}
}
int main() {
	system("pause>null");
	load(20);
	int choice;
back:choice = menu();
	switch (choice) {
	case 1:
		cout << "GET CREDENTIALS ..." << endl;
		load(20);
		get_data();
		casino();
		break;
	case 2:
		load(20);
		cout << "ABOUT ..." << endl;
		about();
		goto back;
		break;
	case 3:
		load(20);
		cout << endl << "EXIT";
		exit(0);
		break;
	default:
		load(10);
		cout << "INVALID INPUT !!" << endl;
		goto back;
	}
	system("pause>0");
}