#include<iostream>
#include<conio.h>
#include<time.h>
#include<windows.h>

using namespace std;

int life = 0;
int amount = 0;
int range_ref;
int range;

void color(int color) {
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color);
}
void welcome() {
	color(9);
	cout << "## WELCOME TO CASINO ##" << endl;
	color(8);
	cout << "^^ A TERMINAL ROULETTE !! ^^" << endl;
	cout << " * % DEVELOPED BY NARASIMHA MURTHY % *" << endl;
	cout << endl;
	color(7);
	cout << "PRESS ANY KEY TO CONTINUE !! ";
}
void load(int k) {
	char x = 219;
	cout << "//// CASINO ////" << endl;
	for (int i = 0; i <= 16 ; i++)
	{
        cout << x;
		Sleep(k);
	}
	cout << endl;
	system("cls");
}

void gotoxy(int x, int y) {
	COORD c;
	c.X = x;
	c.Y = y;
	SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE), c);
}

int menu() {
	int counter = 2;
	char key;
	int set[] = { 7,7,7 };
	gotoxy(0, 0);
	color(8);
	cout << "* * * * CASINO * * * *" << endl;
	gotoxy(0, 1);
	cout << "----------------------" << endl;
	color(set[0]);

	for (int i = 0;;) {
		gotoxy(0, 2);
		color(set[0]);
		cout << "1. PLAY ";

		gotoxy(0, 3);
		color(set[1]);
		cout << "2. ABOUT";
		
		gotoxy(0, 4);
		color(set[2]);
		cout << "3. EXIT";

		gotoxy(0, 5);
		color(6);
		cout << "________________________________________" << endl;
		cout << " USE ARROW KEYS TO SELECT YOUR OPTION !! ";
		
		color(3);
		key = _getch();

		if (key == 72 && (counter >= 2 && counter <= 3)) {
			counter--;
		}
		if (key == 80 && (counter >= 1 && counter <= 2)) {
			counter++;
		}
		set[0] = 7;
		set[1] = 7;
		set[2] = 7;

		if (key == '\r') {
			if (counter == 1) {
				return 1;
			}
			if (counter == 2) {
				return 2;
			}
			if (counter == 3) {
				return 3;
			}
		}
		if (counter == 1) {
			set[0] = 10;
		}
		if (counter == 2) {
			set[1] = 10;
		}
		if (counter == 3) {
			set[2] = 10;
		}
	}
	color(7);

}

void get_data() {
	system("cls");
	cout << " ENTER TOTAL AMOUNT : "; cin >> amount;
	cout << " ENTER MAXIMUM LIFES : "; cin >> life;
	back:cout << " ENTER THE RANGE : "; cin >> range_ref;
	if (range_ref > 0) {
		range = range_ref;
	}
	else {
		cout << "RANGE CANNOT BE NEGATIVE !! " << endl;
		goto back;
	}
}

void try_ag() {
	system("cls");
	cout << "YOU LOST A LIFE ! TRY AGAIN " << endl;
	cout << "----------------------------";
	life--;
}

int random() {
	srand(time(0));
	int ref_rand = rand() % range;
	ref_rand = 3;
	return ref_rand;
}

void lose() {
	cout << "YOU LOSE ! ";
}

void win() {
	system("cls");
	cout << "CONGRATULATIONS !! " << endl;
	cout << "YOU WON !! " << endl;
	system("pause>0");
	cout << "PRESS ANY KEY TO CONTINUE !!" << endl;
}

void casino() {
	int guess;
    int bet_amt;
	int RANDOM = random();
	while ((amount != 0)) {
		come:system("cls");
		if (life == 0 || amount == 0) {
			lose();
			break;
		} else {
			cout << "LIFE : " << life << endl;
			cout << "RANGE : " << range << endl;
			cout << "BALANCE : " << amount << endl;
			loop1:cout << "ENTER BET AMOUNT : "; cin >> bet_amt;
			cout << "---- ----- -------- ----- ---------- ---- " << endl;
			if (bet_amt > amount) {
				cout << "INVALID BET !!  " << endl << endl;
				goto loop1;
			}
			else {
				cout << "ENTER YOUR GUESS !! : "; cin >> guess;
				if (guess == RANDOM) {
					amount = amount + bet_amt;
					win();
				}
				else {
					if (amount == 0 || life==0) {
						goto come;
					}
					else {
						amount = amount - bet_amt;
						cout << "LOST LIFE ! " << endl;
					}
			 		if (amount != 0 && life != 0) {
						try_ag();
					}
					else {
						goto come;
					}
			}
		  }
		}
	}
}
void about() {
	system("cls");
	cout << "-> This is a simple gambling game which is currently under development\nThis game is currently available for single players  " << endl;
	cout << " **** HOW TO PLAY ****" << endl;
	cout << "1. Player needs to enter total amount, range for guess and life parameters." << endl;
	cout << "2. And player starts the game by betting amount " << endl;
	cout << "3. The player should guess the number that is randomly generated by the COMPUTER " << endl;
	cout << "4. If the player will guess the number, then the betted amount is added to the amount or else it is deducted " << endl;
	cout << "4. If player looses all the lifes then he is eleminated from the game " << endl;
	cout << " ---- CLICK E TO GO BACK TO MENU ----" << endl;
	cout << "---- DEVELOPED OFFICIALLY BY NARASIMHA MURTHY ----" << endl;
	char a;
here:a = _getch();
	if ((a == 'E') || (a == 'e')) {
		system("cls");
	}
	else {
		cout << endl << "TRY AGAIN !! " << endl;
		goto here;
	}
}
int main() {
	welcome();
	system("pause>null");
	cout << endl;
	load(20);
	int choice;
back:choice = menu();
	switch (choice) {
	case 1:
		cout << "GET CREDENTIALS ..." << endl;
		load(20);
		get_data();
		casino();
		break;
	case 2:
		load(20);
		cout << "ABOUT ..." << endl;
		about();
		goto back;
		break;
	case 3:
		load(20);
		cout << endl << "EXIT";
		exit(0);
		break;
	default:
		load(10);
		cout << "INVALID INPUT !!" << endl;
		goto back;
	}
	system("pause>0");
}			 						